[package]
name = "zas"
version = "0.17.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]
description = "Local development made easy"
license = "MIT"
homepage = "https://github.com/juanibiapina/zas"
readme = "README.md"

[dependencies]
hyper = "*"
futures = "*"
regex = "*"
tokio-core = "*"

[lib]
doc = false

[[bin]]
name = "zasd"
